### ISSUE TITLE
winston-logstash-udp

### ISSUE THREAD

**Issue by yb8749** [sazze/winston-logstash-udp#12]
when i used your winston-logstash-udp i received unexpected token but i found different example on web that worked the different between them was [{ -> [ (transports) 
 transports: [
    new (LogstashUDP)({
          port: 555,
          appName: 'YBWinston',
          host: '10.70.23.16'
          //host: '172.17.42.1'
        })
      ]

**Comment by cthayer** [comment]
@yb8749 Thanks!  I've updated the documentation.
